# Generated by Django 5.1.5 on 2025-03-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pub_date',
            new_name='create_date',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('products', models.ManyToManyField(related_name='categories', to='app.product')),
            ],
        ),
    ]
